import { Footer } from '@/components/modules/footer'
import { Header } from '@/components/modules/header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Bootstrap } from './bootstrap'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Bootstrap>
          <Header />
          <main className='min-h-screen bg-dark flex-1'>{children}</main>
          <Footer />
        </Bootstrap>
      </body>
    </html>
  )
}
